version: 2

sources:
  - name: source_crm
    database: POC2
    schema: PUBLIC_BRONZE
    tables:
      - name: crm_cust_info
      - name: crm_prd_info
      - name: crm_sales_details
  - name: source_erp
    database: POC2
    schema: PUBLIC_BRONZE
    tables:
      - name: erp_loc_a101
      - name: erp_cust_az12
      - name: erp_px_cat_g1v2
