version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
  - name: dim_products
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
  - name: fact_sales
    columns:
      - name: order_number
        tests:
          - not_null
      - name: product_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_key
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_key
